"""
MongoDB repository for chat sessions and messages.

Design:
- ChatRepository handles both chat_sessions and messages collections
- save_message() returns the full document with generated _id
- get_context_messages() returns last N messages for Redis rebuild
- All ObjectIds serialised as strings at the boundary

ID Strategy:
- `_id` / `user_id` / `session_id` references use MongoDB-native ObjectId ONLY when
  the value is a real 24-hex ObjectId string (i.e. user._id generated by Mongo).
- `session_id` values are UUID-format strings produced by SessionManager — they are
  stored as plain strings and queried with plain-string equality, NOT ObjectId().
"""

from __future__ import annotations

from datetime import datetime, timezone

from bson import ObjectId
from loguru import logger
from pymongo.errors import OperationFailure

from app.infrastructure.db.mongodb import chat_sessions_col, get_database, messages_col


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _to_object_id(value: str) -> ObjectId | str:
    """
    Try to convert value to ObjectId.
    Falls back to the raw string when the value is not a valid 24-hex ObjectId
    (e.g. UUID strings from SessionManager).
    """
    try:
        return ObjectId(value)
    except Exception:
        return value


def _derive_session_title(content: str, max_len: int = 30) -> str:
    return content.strip()[:max_len]


# ── Chat Sessions ─────────────────────────────────────────────────────────────


async def create_chat_session(
    user_id: str,
    title: str = "New Chat",
    session_id: str | None = None,
) -> dict:
    """
    Insert a new chat session document.
    Returns the created document with string _id.
    """
    doc = {
        **({"_id": _to_object_id(session_id)} if session_id is not None else {}),
        "user_id": _to_object_id(user_id),  # real Mongo ObjectId if user_id is a Mongo _id
        "title": title,
        "created_at": _now(),
        "updated_at": _now(),
        "message_count": 0,
        "is_archived": False,
    }
    result = await chat_sessions_col().insert_one(doc)
    doc["_id"] = result.inserted_id
    doc["user_id"] = user_id
    logger.debug(f"Chat session created | id={doc['_id']} | user={user_id}")
    return _serialise_session(doc)


async def get_chat_session(session_id: str) -> dict | None:
    """Fetch a chat session by id."""
    sid = _to_object_id(session_id)
    doc = await chat_sessions_col().find_one({"_id": sid})
    if doc is None:
        return None
    return _serialise_session(doc)


async def touch_chat_session(session_id: str) -> None:
    """Update updated_at timestamp for an active session."""
    sid = _to_object_id(session_id)
    try:
        await chat_sessions_col().update_one(
            {"_id": sid},
            {"$set": {"updated_at": _now()}},
        )
    except Exception as e:
        logger.warning(f"Failed to touch session {session_id}: {e}")


async def list_user_sessions(
    user_id: str,
    archived: bool = False,
    limit: int = 50,
) -> list[dict]:
    """Return sessions for a user, newest first (by updated_at)."""
    uid = _to_object_id(user_id)
    cursor = (
        chat_sessions_col()
        .find({"user_id": uid, "is_archived": archived})
        .sort("updated_at", -1)
        .limit(limit)
    )
    return [_serialise_session(doc) async for doc in cursor]


async def archive_chat_session(session_id: str) -> None:
    """Soft-delete a session by marking it archived."""
    sid = _to_object_id(session_id)
    await chat_sessions_col().update_one(
        {"_id": sid},
        {"$set": {"is_archived": True}},
    )


async def delete_chat_session(session_id: str) -> bool:
    """
    Physically delete a chat session and all its associated messages.
    Returns True if a session was deleted.
    """
    sid = _to_object_id(session_id)

    # Delete messages first
    await messages_col().delete_many({"session_id": sid})

    # Delete the session
    result = await chat_sessions_col().delete_one({"_id": sid})

    logger.info(f"Physically deleted session and messages | session_id={session_id} | deleted_count={result.deleted_count}")
    return result.deleted_count > 0


def _format_datetime(dt: datetime | None) -> str | None:
    if not dt:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt.isoformat().replace("+00:00", "Z")


def _serialise_session(doc: dict) -> dict:
    """Stringify ObjectIds in a session document."""
    return {
        "id": str(doc["_id"]),
        "user_id": str(doc["user_id"]),
        "title": doc.get("title", ""),
        "created_at": _format_datetime(doc.get("created_at")),
        "updated_at": _format_datetime(doc.get("updated_at") or doc.get("last_active")),
        "message_count": doc.get("message_count", 0),
        "is_archived": doc.get("is_archived", False),
    }


# ── Messages ──────────────────────────────────────────────────────────────────


async def save_message(
    session_id: str,
    role: str,
    content: str,
    input_type: str = "text",
    tts_cache_key: str | None = None,
    sources: list[dict] | None = None,
) -> dict:
    """
    Insert a message and increment the parent session's message_count.
    Returns the created document with string _id.

    session_id may be a UUID string (from SessionManager) or a Mongo ObjectId string.
    _to_object_id() handles both cases safely.
    """
    sid = _to_object_id(session_id)
    doc = {
        "session_id": sid,
        "role": role,
        "content": content,
        "input_type": input_type,
        "tts_cache_key": tts_cache_key,
        "sources": sources or [],
        "timestamp": _now(),
    }

    try:
        async with await get_database().client.start_session() as session:
            async with session.start_transaction():
                result = await messages_col().insert_one(doc, session=session)
                doc["_id"] = str(result.inserted_id)
                doc["session_id"] = session_id

                if role == "user":
                    session_title = _derive_session_title(content)
                    if session_title:
                        await chat_sessions_col().update_one(
                            {"_id": sid, "title": "New Chat"},
                            {"$set": {"title": session_title}},
                            session=session
                        )

                # Increment session counters
                await chat_sessions_col().update_one(
                    {"_id": sid},
                    {
                        "$inc": {"message_count": 1},
                        "$set": {"updated_at": _now()},
                    },
                    session=session
                )
    except OperationFailure:
        # Fallback without transaction
        result = await messages_col().insert_one(doc)
        doc["_id"] = str(result.inserted_id)
        doc["session_id"] = session_id

        if role == "user":
            session_title = _derive_session_title(content)
            if session_title:
                await chat_sessions_col().update_one(
                    {"_id": sid, "title": "New Chat"},
                    {"$set": {"title": session_title}},
                )

        # Increment session counters
        await chat_sessions_col().update_one(
            {"_id": sid},
            {
                "$inc": {"message_count": 1},
                "$set": {"updated_at": _now()},
            },
        )

    return doc


async def get_session_messages(
    session_id: str,
    limit: int = 50,
) -> list[dict]:
    """
    Fetch the last `limit` messages for a session (oldest → newest).
    Used to rebuild Redis chat context on a cache miss.
    """
    sid = _to_object_id(session_id)
    # Fetch in reverse order (newest first), then reverse to get oldest first
    cursor = messages_col().find({"session_id": sid}).sort("timestamp", -1).limit(limit)
    docs = [doc async for doc in cursor]
    docs.reverse()  # oldest → newest for context building
    return [_serialise_message(d) for d in docs]


async def get_message_count(session_id: str) -> int:
    """Count messages in a session (for stats)."""
    sid = _to_object_id(session_id)
    return await messages_col().count_documents({"session_id": sid})


def _serialise_message(doc: dict) -> dict:
    """Stringify ObjectIds in a message document."""
    return {
        "id": str(doc["_id"]),
        "session_id": str(doc["session_id"]),
        "role": doc.get("role", ""),
        "content": doc.get("content", ""),
        "input_type": doc.get("input_type", "text"),
        "tts_cache_key": doc.get("tts_cache_key"),
        "sources": doc.get("sources", []),
        "timestamp": _format_datetime(doc.get("timestamp")),
    }


from app.domain.chat.ports import ChatRepositoryPort


class MongoChatRepository(ChatRepositoryPort):
    """Concrete implementation of ChatRepositoryPort using MongoDB."""

    async def create_chat_session(self, user_id: str, title: str = "New Chat", session_id: str | None = None) -> dict:
        return await create_chat_session(user_id=user_id, title=title, session_id=session_id)

    async def get_chat_session(self, session_id: str) -> dict | None:
        return await get_chat_session(session_id=session_id)

    async def touch_chat_session(self, session_id: str) -> None:
        return await touch_chat_session(session_id=session_id)

    async def list_user_sessions(self, user_id: str, archived: bool = False, limit: int = 50) -> list[dict]:
        return await list_user_sessions(user_id=user_id, archived=archived, limit=limit)

    async def archive_chat_session(self, session_id: str) -> None:
        return await archive_chat_session(session_id=session_id)

    async def delete_chat_session(self, session_id: str) -> bool:
        return await delete_chat_session(session_id=session_id)

    async def save_message(self, session_id: str, role: str, content: str, input_type: str = "text", tts_cache_key: str | None = None, sources: list[dict] | None = None) -> dict:
        return await save_message(session_id=session_id, role=role, content=content, input_type=input_type, tts_cache_key=tts_cache_key, sources=sources)

    async def get_session_messages(self, session_id: str, limit: int = 50) -> list[dict]:
        return await get_session_messages(session_id=session_id, limit=limit)

    async def get_message_count(self, session_id: str) -> int:
        return await get_message_count(session_id=session_id)
