"""
MongoDB repository for chat sessions and messages.

Design:
- ChatRepository handles both chat_sessions and messages collections
- save_message() returns the full document with generated _id
- get_context_messages() returns last N messages for Redis rebuild
- All ObjectIds serialised as strings at the boundary

ID Strategy:
- `_id` / `user_id` / `session_id` references use MongoDB-native ObjectId ONLY when
  the value is a real 24-hex ObjectId string (i.e. user._id generated by Mongo).
- `session_id` values are UUID-format strings produced by SessionManager — they are
  stored as plain strings and queried with plain-string equality, NOT ObjectId().
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from bson import ObjectId
from loguru import logger

from app.infrastructure.db.mongodb import chat_sessions_col, messages_col


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _to_object_id(value: str) -> ObjectId | str:
    """
    Try to convert value to ObjectId.
    Falls back to the raw string when the value is not a valid 24-hex ObjectId
    (e.g. UUID strings from SessionManager).
    """
    try:
        return ObjectId(value)
    except Exception:
        return value


# ── Chat Sessions ─────────────────────────────────────────────────────────────


async def create_chat_session(
    user_id: str,
    title: str = "New Chat",
    session_id: str | None = None,
) -> dict:
    """
    Insert a new chat session document.
    Returns the created document with string _id.
    """
    doc = {
        **({"_id": _to_object_id(session_id)} if session_id is not None else {}),
        "user_id": _to_object_id(user_id),  # real Mongo ObjectId if user_id is a Mongo _id
        "title": title,
        "created_at": _now(),
        "last_active": _now(),
        "message_count": 0,
        "is_archived": False,
    }
    result = await chat_sessions_col().insert_one(doc)
    doc["_id"] = str(result.inserted_id)
    doc["user_id"] = str(user_id)
    logger.debug(f"Chat session created | id={doc['_id']} | user={user_id}")
    return doc


async def get_chat_session(session_id: str) -> Optional[dict]:
    """Fetch a chat session by id."""
    sid = _to_object_id(session_id)
    doc = await chat_sessions_col().find_one({"_id": sid})
    if doc is None:
        return None
    return _serialise_session(doc)


async def touch_chat_session(session_id: str) -> None:
    """Update last_active timestamp for an active session."""
    sid = _to_object_id(session_id)
    try:
        await chat_sessions_col().update_one(
            {"_id": sid},
            {"$set": {"last_active": _now()}},
        )
    except Exception as e:
        logger.warning(f"Failed to touch session {session_id}: {e}")


async def list_user_sessions(
    user_id: str,
    archived: bool = False,
    limit: int = 50,
) -> list[dict]:
    """Return sessions for a user, newest first (by last_active)."""
    uid = _to_object_id(user_id)
    cursor = (
        chat_sessions_col()
        .find({"user_id": uid, "is_archived": archived})
        .sort("last_active", -1)
        .limit(limit)
    )
    return [_serialise_session(doc) async for doc in cursor]


async def archive_chat_session(session_id: str) -> None:
    """Soft-delete a session by marking it archived."""
    sid = _to_object_id(session_id)
    await chat_sessions_col().update_one(
        {"_id": sid},
        {"$set": {"is_archived": True}},
    )


def _serialise_session(doc: dict) -> dict:
    """Stringify ObjectIds in a session document."""
    return {
        "id": str(doc["_id"]),
        "user_id": str(doc["user_id"]),
        "title": doc.get("title", ""),
        "created_at": doc.get("created_at"),
        "last_active": doc.get("last_active"),
        "message_count": doc.get("message_count", 0),
        "is_archived": doc.get("is_archived", False),
    }


# ── Messages ──────────────────────────────────────────────────────────────────


async def save_message(
    session_id: str,
    role: str,
    content: str,
    input_type: str = "text",
    tts_cache_key: Optional[str] = None,
    sources: Optional[list[dict]] = None,
) -> dict:
    """
    Insert a message and increment the parent session's message_count.
    Returns the created document with string _id.

    session_id may be a UUID string (from SessionManager) or a Mongo ObjectId string.
    _to_object_id() handles both cases safely.
    """
    sid = _to_object_id(session_id)
    doc = {
        "session_id": sid,
        "role": role,
        "content": content,
        "input_type": input_type,
        "tts_cache_key": tts_cache_key,
        "sources": sources or [],
        "timestamp": _now(),
    }
    result = await messages_col().insert_one(doc)
    doc["_id"] = str(result.inserted_id)
    doc["session_id"] = session_id

    # Increment session counters — use same sid type for consistency
    await chat_sessions_col().update_one(
        {"_id": sid},
        {
            "$inc": {"message_count": 1},
            "$set": {"last_active": _now()},
        },
    )

    return doc


async def get_session_messages(
    session_id: str,
    limit: int = 50,
) -> list[dict]:
    """
    Fetch the last `limit` messages for a session (oldest → newest).
    Used to rebuild Redis chat context on a cache miss.
    """
    sid = _to_object_id(session_id)
    # Fetch in reverse order (newest first), then reverse to get oldest first
    cursor = messages_col().find({"session_id": sid}).sort("timestamp", -1).limit(limit)
    docs = [doc async for doc in cursor]
    docs.reverse()  # oldest → newest for context building
    return [_serialise_message(d) for d in docs]


async def get_message_count(session_id: str) -> int:
    """Count messages in a session (for stats)."""
    sid = _to_object_id(session_id)
    return await messages_col().count_documents({"session_id": sid})


def _serialise_message(doc: dict) -> dict:
    """Stringify ObjectIds in a message document."""
    return {
        "id": str(doc["_id"]),
        "session_id": str(doc["session_id"]),
        "role": doc.get("role", ""),
        "content": doc.get("content", ""),
        "input_type": doc.get("input_type", "text"),
        "tts_cache_key": doc.get("tts_cache_key"),
        "sources": doc.get("sources", []),
        "timestamp": doc.get("timestamp"),
    }
