"""Audit UUID identity and auth/session consistency.

This script is intentionally non-destructive. It reports:
- orphaned database relations
- stale chat sessions
- invalid user auth state
- malformed Redis refresh/session auth records

Use --write-cleanup to generate SQL that deletes only clear orphan records.
Review the generated SQL before running it.
"""

from __future__ import annotations

import argparse
import asyncio
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy import text

from app.infrastructure.cache.redis_client import close_redis, get_redis, init_redis
from app.infrastructure.db.database import AsyncSessionLocal, close_db
from app.shared.ids import parse_uuid
from app.shared.security import decode_auth_token


async def _scalar(db, sql: str, params: dict[str, Any] | None = None) -> int:
    result = await db.execute(text(sql), params or {})
    return int(result.scalar() or 0)


async def audit_database(stale_days: int) -> dict[str, Any]:
    async with AsyncSessionLocal() as db:
        return {
            "orphan_chat_sessions": await _scalar(
                db,
                """
                SELECT COUNT(*)
                FROM chat_sessions cs
                LEFT JOIN users u ON u.id = cs.user_id
                WHERE u.id IS NULL
                """,
            ),
            "orphan_messages": await _scalar(
                db,
                """
                SELECT COUNT(*)
                FROM messages m
                LEFT JOIN chat_sessions cs ON cs.id = m.session_id
                WHERE cs.id IS NULL
                """,
            ),
            "orphan_documents": await _scalar(
                db,
                """
                SELECT COUNT(*)
                FROM documents d
                LEFT JOIN users u ON u.id = d.user_id
                WHERE u.id IS NULL
                """,
            ),
            "orphan_document_chunks": await _scalar(
                db,
                """
                SELECT COUNT(*)
                FROM document_chunks dc
                LEFT JOIN documents d ON d.id = dc.document_id
                WHERE d.id IS NULL
                """,
            ),
            "negative_refresh_versions": await _scalar(
                db,
                "SELECT COUNT(*) FROM users WHERE refresh_token_version < 0",
            ),
            "stale_chat_sessions": await _scalar(
                db,
                """
                SELECT COUNT(*)
                FROM chat_sessions
                WHERE updated_at < NOW() - (:stale_days * INTERVAL '1 day')
                """,
                {"stale_days": stale_days},
            ),
            "stale_incomplete_documents": await _scalar(
                db,
                """
                SELECT COUNT(*)
                FROM documents
                WHERE current_stage IN ('QUEUED', 'UPLOADING', 'PARSING', 'CHUNKING', 'EMBEDDING', 'INDEXING')
                  AND upload_date < NOW() - INTERVAL '1 day'
                """,
            ),
        }


async def audit_redis() -> dict[str, Any]:
    await init_redis()
    redis = get_redis()
    malformed_refresh_tokens: list[str] = []
    malformed_auth_sessions: list[str] = []

    async for key in redis.scan_iter(match="auth:refresh:*", count=100):
        key_str = key.decode("utf-8") if isinstance(key, bytes) else str(key)
        raw = await redis.get(key)
        token = raw.decode("utf-8") if isinstance(raw, bytes) else raw
        if not isinstance(token, str):
            malformed_refresh_tokens.append(key_str)
            continue
        try:
            decode_auth_token(token, expected_type="refresh")
        except Exception:
            malformed_refresh_tokens.append(key_str)

    async for key in redis.scan_iter(match="virtai:auth:session:*", count=100):
        key_str = key.decode("utf-8") if isinstance(key, bytes) else str(key)
        user_id = key_str.rsplit(":", 1)[-1]
        if parse_uuid(user_id) is None:
            malformed_auth_sessions.append(key_str)

    await close_redis()
    return {
        "malformed_refresh_token_keys": malformed_refresh_tokens,
        "malformed_auth_session_keys": malformed_auth_sessions,
    }


def cleanup_sql(stale_days: int) -> str:
    return f"""-- Generated by scripts/audit_auth_identity.py
-- Review before running. These statements remove only orphaned dependent rows.

BEGIN;

DELETE FROM messages m
WHERE NOT EXISTS (
    SELECT 1 FROM chat_sessions cs WHERE cs.id = m.session_id
);

DELETE FROM document_chunks dc
WHERE NOT EXISTS (
    SELECT 1 FROM documents d WHERE d.id = dc.document_id
);

DELETE FROM documents d
WHERE NOT EXISTS (
    SELECT 1 FROM users u WHERE u.id = d.user_id
);

DELETE FROM chat_sessions cs
WHERE NOT EXISTS (
    SELECT 1 FROM users u WHERE u.id = cs.user_id
);

-- Recommended manual review for stale sessions:
-- SELECT * FROM chat_sessions
-- WHERE updated_at < NOW() - INTERVAL '{stale_days} days';

COMMIT;
"""


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stale-days", type=int, default=30)
    parser.add_argument("--write-cleanup", type=Path)
    args = parser.parse_args()

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "database": await audit_database(stale_days=args.stale_days),
        "redis": await audit_redis(),
        "recommendations": [
            "Delete orphan rows only after a backup or transaction dry run.",
            "Clear malformed Redis refresh/session keys; clients will re-authenticate.",
            "Review stale chat sessions by age and product retention policy before deleting.",
            "Investigate stale incomplete documents before marking failed or cancelled.",
        ],
    }

    print(json.dumps(report, indent=2, sort_keys=True))

    if args.write_cleanup:
        args.write_cleanup.write_text(cleanup_sql(args.stale_days), encoding="utf-8")
        print(f"\ncleanup_sql={args.write_cleanup}")

    await close_db()


if __name__ == "__main__":
    asyncio.run(main())
