from collections.abc import AsyncIterator
from typing import Protocol


class StorageProvider(Protocol):
    async def save(
        self, key: str, data: bytes, content_type: str = "application/octet-stream"
    ) -> str: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def open(self, key: str) -> AsyncIterator[bytes]: ...
    async def get_bytes(self, key: str) -> bytes: ...
