"""Add QuizAttempt and QuizAttemptAnswer tables

Revision ID: 1f587d96a315
Revises: 20260627_add_doc_indexes
Create Date: 2026-06-27 21:37:06.434350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f587d96a315'
down_revision: Union[str, Sequence[str], None] = '20260629_cascade_session_fk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    if 'quiz_attempt_answers' in inspector.get_table_names():
        return  # Migration was already applied in this environment
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.Column('hesitation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_chat_sessions_user_last_message'), table_name='chat_sessions')
    op.create_index('ix_chat_sessions_user_last_message', 'chat_sessions', ['user_id', 'last_message_at'], unique=False)
    op.create_index('ix_chunks_text_gin', 'document_chunks', [sa.literal_column("to_tsvector('english', chunk_text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_documents_scope_id'), table_name='documents')
    op.drop_column('quiz_attempts', 'answers')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.add_column('quiz_attempts', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_documents_scope_id'), 'documents', ['scope_id'], unique=False)
    op.drop_index('ix_chunks_text_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chat_sessions_user_last_message', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_last_message'), 'chat_sessions', ['user_id', sa.literal_column('last_message_at DESC')], unique=False)
    op.drop_table('quiz_attempt_answers')
    # ### end Alembic commands ###
