"""add visualization cache

Revision ID: 20260623_visualization_cache
Revises: 20260623_diagram_cache
Create Date: 2026-06-23 09:48:00.000000

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260623_visualization_cache"
down_revision: Union[str, Sequence[str], None] = "20260623_diagram_cache"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualization_cache',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualization_cache')
    # ### end Alembic commands ###
